### ISSUE TITLE
Cache syncing from informer

### ISSUE THREAD

**Issue by PhilipGough** [3scale/kourier#10]
Hey @davidor, @jmprusi - on startup, there is a local indexing going on by the informer so because there are ~75 endpoints in your cluster, you are going to get 75 create events on your channel.

It makes sense when you think about it because if you crash etc then you dont want to miss events so your code to deal with these events should be idempotent.

Other than that you are not making use of the queue. The informer has a queue and in the watcher function you should be queuing up those objects so the worker can take them off the queue and handle them as required by looking up the cache.

For the updates you want to cast back into the original runtime.Object and compare the resource version ignoring ones that are the same and enqueing new objects where they have changed, assuming you don't need to explicitly handle the older revision.

Hope that helps some

**Comment by davidor** [comment]
Hey @PhilipGough thanks for your input.

There are a few things that I don't fully understand. I'm still learning all of this :sweat_smile: 

If I understood correctly, you are suggesting to keep a reference to the store created by `cache.NewInformer`, read what's in there, and react accordingly. Is that right?

I'm not sure if that's what we need. Maybe I'm missing something. For now, we are not interested in analyzing each event. Once we receive an event that's relevant for our use case (changes in endpoints, changes in Knative servings, etc.) we just want to reload the whole config. In the future, we might want to revisit this and refresh only specific parts of the Envoy config.

I'm thinking about an alternative solution. I think that using a buffered channel might help. The problem we have is that sometimes, like on boot, there are many events produced in a short interval, and instead of refreshing the config once per event, we'd like it to refresh it just once. I'm thinking that we could use a buffered channel with capacity 10 or something like this. If the watcher is fast and produces 10 consecutive events, in the `main`, we could refresh just one and clear the channel. Do you think that's a good solution?

**Comment by PhilipGough** [comment]
Those events are coming from your informer doing a cache sync for local indexing. https://github.com/3scale/kourier/blob/master/pkg/kubernetes/kubernetes.go#L56

On boot, you will see create events for each object you are watching as the cache sync occurs. There should be a way you can ignore events until the full sync is done. 

I'm suggesting you should use the in-built queueing functionality and run a worker to take from the queue and do look ups on the local cache if that's what needs doing. 

Take a look at the example project for some ideas and see if it matches your use case https://github.com/kubernetes/sample-controller

**Comment by jmprusi** [comment]
what about using the controller-runtime? 

https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/controller#example-New

**Comment by PhilipGough** [comment]
@jmprusi for sure would extract some of the internals from you. But in the end you either need them or you don't, right? If you don't, then a watch directly via the client might be sufficient
